server:
  port: 8080
  servlet:
    session:
      #默认30分钟
      timeout: 30m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.252.53:3306/new_mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Kexin!00
  redis:
    host: 127.0.0.1
    port: 6379
    password: oshacker
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: root
    password: 123456

# 在数据库字段映射成pojo方面，BaseResultMap比map-underscore-to-camel-case的功能更强大
mybatis:
  mapper-locations: classpath:mappers/*.xml
  # 控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    map-underscore-to-camel-case: true

# 修改控制台输出格式
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

